/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.ContextFactory;
import hr.algebra.model.Plant;
import hr.algebra.parsers.rss.PlantParser;
import hr.algebra.utilities.MessageUtils;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author lorena
 */
public class UploadPlantsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UploadPlantsPanel
     */
    public UploadPlantsPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsPlants = new javax.swing.JList<>();
        btnUploadPlants = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lsPlants.setToolTipText("");
        lsPlants.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lsPlantsComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(lsPlants);

        btnUploadPlants.setText("upload");
        btnUploadPlants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPlantsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(btnUploadPlants)
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadPlants)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadPlantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPlantsActionPerformed
        try {
            List<Plant> plants = PlantParser.parse();
            //repository.createPlants(plants);
            loadModel();

        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Unrecoverable error", "Unable to upload plants");
            System.exit(1);
        }
    }//GEN-LAST:event_btnUploadPlantsActionPerformed

    private void lsPlantsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lsPlantsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lsPlantsComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUploadPlants;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Plant> lsPlants;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel<Plant> plantsModel;
    private Repository repository;

    private void init() {
        try {
            //repository = ContextFactory.getRepository();
            plantsModel = new DefaultListModel<>();
            loadModel();
        } catch (Exception ex) {
            Logger.getLogger(UploadPlantsPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    private void loadModel() throws Exception {
        //List<Plant> plants = repository.getAllPlants();
        plantsModel.clear();
        //plants.forEach(plantsModel::addElement);
        lsPlants.setModel(plantsModel);
    }
}
